version: "3.7"
services:
  db:
    image: "postgres:15.4"
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - PGUSER=${DB_USER}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: "pg_isready -U ${DB_USER} -d ${DB_NAME}"
      interval: 1s
      timeout: 5s
      retries: 10
volumes:
  db:
    driver: local
