version: "3.7"
services:
  db:
    image: "postgres:15.4"
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=things
      - POSTGRES_PASSWORD=pg-pw
      - POSTGRES_DB=things
volumes:
  db:
    driver: local
