name: go

on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
# TODO add github actions extension to .nix

jobs:
  setup-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.4
  test:
    needs: [setup-go]
    runs-on: ubuntu-latest
    steps:
      - run: cat Makefile
      - run: pwd
      - name: test
        run: make test
  vulncheck:
    needs: [setup-go]
    runs-on: ubuntu-latest
    steps: 
      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest
        shell: bash
      - name: Run vulncheck
        run: govulncheck
        shell: bash