name: go

on: [push] # TODO should this just be merge request + main branch?
# TODO add github actions extension to .nix

env:
  GO_VERSION: 1.22.4

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: $GO_VERSION
      - name: Go version
        run: go version