name: go

on: [push] # TODO should this just be merge request + main branch?
# TODO add github actions extension to .nix


jobs:
  test:
    runs-on: go-1.22.4
    steps:
      - uses: actions/checkout@v4
      - name: Go version
        run: go version