name: go

on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
# TODO add github actions extension to .nix

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.4
      - name: test
        run: make test
  vulncheck:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.4
      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest
        shell: bash
      - name: Run vulncheck
        run: govulncheck
        shell: bash
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58